version: '3.7'

services:
  virtuoso:
    container_name: virtuoso
    hostname: virtuoso
    user: root
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
    volumes:
      - type: bind
        source: ./databases
        target: /fuseki/databases
    ports:
      - "9030:8890"
  fuseki-cache:
    container_name: skosmos-fuseki-cache
    hostname: fuseki-cache
    image: varnish
    ports:
      - 9031:80
    volumes:
      - type: bind
        source: ./config/varnish-default.vcl
        target: /etc/varnish/default.vcl
  skosmos:
    container_name: skosmos-web
    hostname: skosmos
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.ubuntu
    ports:
      - 9090:80
    depends_on:
      - virtuoso
    volumes:
      - type: bind
        source: ./config/config-docker-compose.ttl
        target: /var/www/html/config.ttl
