version: '3.7'

services:
  virtuoso:
    container_name: virtuoso
    hostname: virtuoso
    user: root
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
    environment:
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
      VIRT_Parameters_TraceOn: "exec" # enhanced logging
    volumes:
      - type: bind
        source: taxonomy-databases
        target: /data
    ports:
      - 9030:8890
  cache:
    container_name: cache
    hostname: cache
    image: varnish
    ports:
      - 9031:80
    volumes:
      - type: volume
        source: taxonomy-config/varnish-default.vcl
        target: /etc/varnish/default.vcl
  skosmos:
    container_name: skosmos-web
    hostname: skosmos
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.ubuntu
    ports:
      - 9090:80
    depends_on:
      - virtuoso
      - cache
    volumes:
      - type: bind
        source: taxonomy-config/config-docker-compose.ttl
        target: /var/www/html/config.ttl
